env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - 1.19.0
  - nightly-2017-07-20
sudo: false
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
script:
  - printf TRAVIS_COMMIT:%s\\n $TRAVIS_COMMIT
  - printf TRAVIS_COMMIT_MESSAGE:%s\\n $TRAVIS_COMMIT_MESSAGE
  - printf TRAVIS_EVENT_TYPE:%s\\n $TRAVIS_EVENT_TYPE
  - printf TRAVIS_PULL_REQUEST:%s\\n $TRAVIS_PULL_REQUEST
  - printf TRAVIS_PULL_REQUEST_SHA:%s\\n $TRAVIS_PULL_REQUEST_SHA
before_deploy:
  - bash cargo_install.sh cargo-config;
  - export LIB_VERSION=$(cargo config package.version | tr -d '"')
  - printf LIB_VERSION:%s\\n $LIB_VERSION
  - cargo build --release
  - mkdir -p target/deploy
  - strip target/release/libsamp.so
  - zip target/deploy/libsamp-v$LIB_VERSION.zip target/release/libsamp.so
  - zip target/deploy/libsamp-mock-v$LIB_VERSION.zip target/release/libsamp.so
deploy:
  provider: s3
  access_key_id: AKIAIA2TXTG7EV5VIG2Q
  secret_access_key:
    secure: qEDay6TCAy3tBLqLYFOx9OjAdoRl010paK2//teFETfwUfJA/RtNSfkp1yrgx+kZ3FO8cthdDnwR3zjM3pkCL+5mGkQMAgvRY7rcEB5H1VyO4jkZRoB4n/yUu5jB4dHdeeRWTOJxNOOPA0G1Q65LLkJql2JGoJatqE3pBmJm0X8=
  bucket: samp-deploy
  local-dir: target/deploy
  upload-dir: $TRAVIS_COMMIT
  acl: public_read
  region: eu-west-2
  skip_cleanup: true
  on:
    branch: master
    tags: false
    condition: "$TRAVIS_EVENT_TYPE = push"
    rust: 1.19.0
after_deploy: rm -rf target/deploy
