env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - gcc-multilib
language: rust
rust:
  - 1.19.0
  - nightly-2017-07-20
sudo: false
cache:
  cargo: true
script:
  - printf TRAVIS_COMMIT:%s\\n $TRAVIS_COMMIT
  - printf TRAVIS_COMMIT_MESSAGE:%s\\n $TRAVIS_COMMIT_MESSAGE
  - printf TRAVIS_EVENT_TYPE:%s\\n $TRAVIS_EVENT_TYPE
  - printf TRAVIS_PULL_REQUEST:%s\\n $TRAVIS_PULL_REQUEST
  - printf TRAVIS_PULL_REQUEST_SHA:%s\\n $TRAVIS_PULL_REQUEST_SHA
before_deploy:
  - mkdir -p target/deploy
  - export LIB_VERSION=v$(cargo pkgid | sed -e "s/.*[:#]\(.*\)/\1/")
  - cargo build --release
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then export SUFFIX=so && strip target/release/libsamp.$SUFFIX; else export SUFFIX=dylib; fi
  - zip target/deploy/samp-$LIB_VERSION-$TRAVIS_OS_NAME-x64.zip target/release/libsamp.$SUFFIX
  - zip target/deploy/samp-mock-$LIB_VERSION-$TRAVIS_OS_NAME-x64.zip target/release/libsamp.$SUFFIX
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then
      (
        set -x;
        rustup target add i686-unknown-linux-gnu &&
        cargo build --release --target=i686-unknown-linux-gnu &&
        strip target/i686-unknown-linux-gnu/release/libsamp.$SUFFIX &&
        zip target/deploy/samp-$LIB_VERSION-$TRAVIS_OS_NAME-x86.zip target/i686-unknown-linux-gnu/release/libsamp.$SUFFIX &&
        zip target/deploy/samp-mock-$LIB_VERSION-$TRAVIS_OS_NAME-x86.zip target/i686-unknown-linux-gnu/release/libsamp.$SUFFIX;
      )
    fi
deploy:
  provider: s3
  access_key_id: AKIAIA2TXTG7EV5VIG2Q
  secret_access_key:
    secure: piiybrNtxz8cwySzb8SUfRTgbd4bgHRHkAb4HOoHSbLSXd9empYC6/a2cArrpNTaZOsNeJzMpHamcbTmNW0yVzCx9FyBxmY+IarDWj9V9C/T4W6FOzD6A/4QJA8a2grqOZuOSeM5DlBHlnu1MKLLuz9AVre7jgyXN+N6RQ0/wZMLqfbIUMfKMrUvvQQ09Dx+zG0qmzuH10Xv7cuvP/yUQ1gBFFzXXrq896FVDcF/64UB8q5sQGc29P2MpSmSpFYBw+q3FBkCTizFjTm2JHBN+NtLXPTmVMq/2TC00W16lQ1NHQV04bni7aPKtYwGOxW0j7AWh6RlHsh+AAjBKMGyn2IJ8+JmsHtTVltGe4U3qbXle6QqML6j/Ik55M0WDyPpuPk5OfObWrvS9aB62oBXaP2LIg3QQnijL0P85QRXrwN0igtAHtJMqHsz8TBCcM8iYEyocvlv5GR1iDADOQvSkM5QfzwvqPCSDwsovJcwouLS1mQgdn1CDo/KyPFRRnw3z0CTdQFBCtvhaUA/uhuOpXTeCSWBV/NIe2/sGgo5Lf8Jl3ukR6ry22jfcdW8KkE9FcksQOMiElcG9iouXhYf5N0WOqscYaDUJHxF3otqgHgB51vHkIX5U02hV26rO/GDulu44Lgc6ndJD4RcZ+jMOC/DuXuK9yKH0LpZ79CNgPM=
  bucket: samp-deploy
  local-dir: target/deploy
  upload-dir: $TRAVIS_COMMIT
  acl: public_read
  region: eu-west-2
  skip_cleanup: true
  on:
    branch: master
    tags: false
    condition: "$TRAVIS_EVENT_TYPE = push"
    rust: 1.19.0
after_deploy: rm -rf target/deploy
