env:
  global:
  - RUST_BACKTRACE=1
  - PATH=$PATH:$HOME/.cargo/bin
os:
- linux
language: rust
rust:
- 1.19.0
sudo: false
script:
- cargo build --release
- mkdir -p target/test
- touch target/test/abcd
- cp target/release/samp target/test/
deploy:
  provider: s3
  access_key_id: AKIAIA2TXTG7EV5VIG2Q
  secret_access_key:
    secure: piiybrNtxz8cwySzb8SUfRTgbd4bgHRHkAb4HOoHSbLSXd9empYC6/a2cArrpNTaZOsNeJzMpHamcbTmNW0yVzCx9FyBxmY+IarDWj9V9C/T4W6FOzD6A/4QJA8a2grqOZuOSeM5DlBHlnu1MKLLuz9AVre7jgyXN+N6RQ0/wZMLqfbIUMfKMrUvvQQ09Dx+zG0qmzuH10Xv7cuvP/yUQ1gBFFzXXrq896FVDcF/64UB8q5sQGc29P2MpSmSpFYBw+q3FBkCTizFjTm2JHBN+NtLXPTmVMq/2TC00W16lQ1NHQV04bni7aPKtYwGOxW0j7AWh6RlHsh+AAjBKMGyn2IJ8+JmsHtTVltGe4U3qbXle6QqML6j/Ik55M0WDyPpuPk5OfObWrvS9aB62oBXaP2LIg3QQnijL0P85QRXrwN0igtAHtJMqHsz8TBCcM8iYEyocvlv5GR1iDADOQvSkM5QfzwvqPCSDwsovJcwouLS1mQgdn1CDo/KyPFRRnw3z0CTdQFBCtvhaUA/uhuOpXTeCSWBV/NIe2/sGgo5Lf8Jl3ukR6ry22jfcdW8KkE9FcksQOMiElcG9iouXhYf5N0WOqscYaDUJHxF3otqgHgB51vHkIX5U02hV26rO/GDulu44Lgc6ndJD4RcZ+jMOC/DuXuK9yKH0LpZ79CNgPM=
  bucket: samp-deploy
  local-dir: target/test
  upload-dir: safe_client_libs/$TRAVIS_COMMIT
  acl: public_read
  skip_cleanup: true